export default {
	FETCHING_TICKER: 'API_FETCHING_TICKER',
	FETCHING_TRADES: 'API_FETCHING_TRADES',
	FETCHING_BOOK: 'API_FETCHING_BOOK',
	UPDATE_PAIR: 'API_UPDATE_PAIR',
	STOP_ALL: 'API_STOP_ALL',
	STOP_TICKER: 'API_STOP_TICKER',
	STOP_TRADES: 'API_STOP_TRADES',
	STOP_BOOK: 'API_STOP_BOOK',
}
